# Generated by Django 6.0.3 on 2026-09-04 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyte', models.CharField(max_length=100, unique=True)),
                ('critical_low', models.FloatField(blank=True, null=True)),
                ('critical_high', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='mg/dL', max_length=20)),
                ('action_required', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('PARA', 'Parasitology'), ('HEMA', 'Hematology'), ('CHEM', 'Chemistry'), ('MICRO', 'Microbiology'), ('IMMUNO', 'Immunology'), ('MOLEC', 'Molecular Biology')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('PARA', 'Parasitology'), ('HEMA', 'Hematology'), ('CHEM', 'Chemistry'), ('MICRO', 'Microbiology'), ('IMMUNO', 'Immunology'), ('MOLEC', 'Molecular Biology')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='sops/')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sops', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
