# Generated by Django 6.0.3 on 2026-09-12 16:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PARA', 'PARASITOLOGY'), ('CHEM', 'Chemistry'), ('HEMA', 'Hematology'), ('MICRO', 'Microbiology'), ('IMMUNO', 'Immunology'), ('MOLEC', 'Molecular Biology'), ('GEN', 'General')], db_index=True, max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('catalog_number', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(default='mL', max_length=20)),
                ('expiry_date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, choices=[('FRIDGE_A', 'Refrigerator A'), ('FRIDGE_B', 'Refrigerator B'), ('FREEZER_A', 'Freezer A'), ('FREEZER_B', 'Freezer B'), ('SHELF_A', 'Shelf A'), ('SHELF_B', 'Shelf B'), ('CABINET_A', 'Cabinet A')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'lot_number'), name='unique_reagent_name_lot')],
            },
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('user', models.CharField(max_length=100)),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='inventory.reagent')),
            ],
            options={
                'ordering': ['-date_used'],
            },
        ),
    ]
